### ISSUE TITLE
Validator `self_delegations` field takes 30s to load

### ISSUE THREAD

**Issue by calvinkei** [forbole/bdjuno#110]
## Bug description
when i query the self_delegations field on validator, it's taking around 30s to load. is there any way to improve the speed?

## Steps to reproduce
query:
```
subscription Validators {
  validator {
    self_delegations(limit: 1, order_by: {height: desc}) {
      amount
    }
    address: consensus_address
    description: validator_descriptions(limit: 1, order_by: { height: desc }) {
      moniker
      avatar_url
      height
    }
    commission: validator_commissions(limit: 1, order_by: { height: desc }) {
      commission
      height
    }
    voting_power: validator_voting_powers(limit: 1, order_by: { height: desc }) {
      voting_power
      height
    }
    status: validator_statuses(limit: 1, order_by: { height: desc }) {
      status
      jailed
      height
    }
  }
}
```

## Expected behavior
load time should ideally be less than 5s

**Comment by rmontagnin** [comment]
I've tried adding some indexes to the involved tables with 35c734603eae50c395315946338697a71fe19923. However, even after doing so, we can see that the analyses of the query highlights that the most expensive operation is the final aggregation: 

![screenshot-gql morpheus desmos network-2021 04 23-13_32_01(1)](https://user-images.githubusercontent.com/9119016/115869340-05f80500-a43e-11eb-91b4-f3f08683d4ba.png)

As the `self_delegations` query is only used to later compute the percentage of self delegated stake that is shown inside the validators list, I think that a possible fix might be to insert such percentage directly inside the `validator` object: 

```graphql
subscription Validators {
  validator {
    self_delegation_percentage // <---
    ...
  }
}
```

This can be done in two ways: 
1. using a computed field
2. creating a new table that contains that value and is linked to the `validator` table

I prefer the first approach, as it is less invasive. But if it fails we can use the second one. 

Anyway, I think this slow query is also due to the load of the server. We might even try expanding the CPU/RAM as it currently is acting as a bottleneck: 

![Screenshot from 2021-04-23 13-28-43](https://user-images.githubusercontent.com/9119016/115869756-a2baa280-a43e-11eb-9142-ee8c16f2efb2.png)

**Comment by rmontagnin** [comment]
Closing as this is now solved
