### ISSUE TITLE
Display genesis transactions

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#116]

**Comment by rmontagnin** [comment]
@ryuash I was taking a look at this issue, and I realized that currently we are handling the genesis in the wrong way. Right now, BDJuno stores the genesis as the block with height `1`, but in reality that block exists and it's the first block that's included when the chain starts: http://lcd.morpheus.desmos.network:1317/blocks/1

In my opinion, we should **not** store the genesis as a block, since it actually is not. Even the genesis transactions are not real transactions, since they do not come with an hash and they are not executed as such. They simply represent the state that should be present when the chain starts. 

For this reason, I think we should not log genesis transactions at all.
