### ISSUE TITLE
Interval checks on proposal status and tally

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#134]
## Feature description 

Two issues:
- Proposals on bdjuno does not update correctly on state changes
- Tally is not being logged on vote
## Implementation proposal

we could run an interval checks on all active proposals and update any status/ tally changes in to bdjuno

**Comment by rmontagnin** [comment]
@ryuash Could you be a little more specific on "Proposals on bdjuno does not update correctly on state changes"? Maybe with an example of when it is not updating? 

I would prefer update the status when something happens rather than periodically. I can fix the tallying by updating the numbers when a vote is submitted

**Comment by ryuash** [comment]
@RiccardoM 
Right now there are a few proposal status changes that bdjuno does not catch:

- When the deposit/voting period ends bdjuno does not update the status to `PROPOSAL_STATUS_REJECTED` or accepted (ex: proposal 4/5/6 in bdjuno)

- when enough users with voting power has officially voted before the voting time ends thus updating the proposal status.

And not really part of this issue but everytime a vote tx happens bdjuno should update the `proposal_tally_result`

**Comment by rmontagnin** [comment]
I've fixed all the above mentioned issues by making so that each proposal that is either in voting or deposit period is checked on each block and its status and tally results are updated properly.

Also, I've introduced a new status in accordance with @ryuash that's `PROPOSAL_STATUS_INVALID` which is used to mark a governance proposal that did **not** pass the deposit period (ie. not enough deposits made to it). This because currently Cosmos deleted the proposals from the status, but we want to persist them. So introducing a new status was the best thing to do.
