### ISSUE TITLE
Osmosis: missing items

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#161]
These are just some things i noticed missing but needed for big dipper 2.0 ui to function properly

- staking params are missing (but i'm using my config file as fallback)
- no snapshots on any proposals
- proposal 2 doesn't seem like it logged correctly (no deposit amount but the proposal passed)
- average block times are missing
- price is missing

At the time of this posting, bdjuno is not fully synced up so i have no idea how accurate the validator and account details page are yet

**Comment by rmontagnin** [comment]
Problems found by looking at the config: 

1. Average block times are missing because the `consensus` module was commented out. It's this module that handles them so if you disable it the average block times will not be stored. 
2. BDJuno did not sync up cause the `listen_new_blocks` was set to `false`. 

It also appeared that it was running using the `cosmos/v0.40.x` branch instead of the `chains/osmosis` one so that's why it was not able to get the correct staking parameters. I will however explore this further along with the proposals and price problems.

**Comment by rmontagnin** [comment]
After looking at everything, the missing data was due to the node having `pruning = "default"`. We always need a `pruning = "nothing"` node to get historical data such as proposal snapshots, deposit amount etc. 

The rest has been fixed with #164
