### ISSUE TITLE
[e-Money] Index stable coin inflation rates

### ISSUE THREAD

**Issue by kwunyeung** [forbole/bdjuno#203]
`e-Money` has customized the `x/mint` in order to allow inflation for the staking token and all stable coins. Inflation of all tokens should be indexed.

https://emoney.validator.network/api/inflation/current

**Comment by huichiaotsou** [comment]
closing with #204

**Comment by rmontagnin** [comment]
@kanniec826 Why was this re-opened? Can we get some details?

**Comment by kanniec826** [comment]
> @kanniec826 Why was this re-opened? Can we get some details?

@RiccardoM There should have some issues between github and zenhub when the PR is merged. The issue should be DONE instead of CLOSE in zenhub when the Sprint hasn’t end, therefore we tried to change the status but it seems causing some issues in github. Kwun and I are thinking a way to solve the issue. I will change them back to CLOSE first until we find another way to do that.
