### ISSUE TITLE
Feature: Manual market cap calculation if not available on coingecko

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#287]
This is requested by Terence but ultimately you guys can decide if this feature is doable or not.

At the moment, a good example would be bitsong: https://www.coingecko.com/en/coins/bitsong. Since the marketcap is unavailable he would like to see if this can be calculated and inserted in to bdjuno manually.

**Comment by MonikaCat** [comment]
Market cap is derived from `circulating supply x current coin price`. It's not possible to find out the current circulating supply value for bitsong chain atm, hence market cap can't be calculated. Unless you mean a market cap derived from `total supply x current coin price` but this wouldn't be comparable to all the other coins and we should probably state that on big dipper. Do you still want me to add it?

**Comment by rmontagnin** [comment]
I totally agree with @MonikaCat, I don't think this is something we should implement on BDJuno. It seems an issue with BitSong and Coingecko that they should resolve (I know for sure that Angelo is working on solving this). We shouldn't have custom logic here in order to avoid having different kind of market cap shown on different chains

**Comment by ryuash** [comment]
Noted. I'll let him know
