### ISSUE TITLE
Get view that select all data need for big dipper

### ISSUE THREAD

**Issue by HarleyAppleChoi** [forbole/bdjuno#38]
## Feature description 
There should be a view set on the database side that gets all data needed for the main page other pages on big dipper so that no need to write a long query in Hasura. 

## Implementation proposal
Implement views statements in the schema.

**Comment by RiccardoM** [comment]
I don't agree in adding a view inside the database, when GraphQL is much more efficient to use instead. The data should be retrieved from the GraphQL endpoint in any case (even having a single view), but with the downside that it cannot be listened out individually. 

@kwunyeung what are your thoughts on this?

**Comment by kwunyeung** [comment]
@RiccardoM I wonder if some aggregation and table join queries will be retrieved more efficiently when there is a view in the database rather than querying fields from multiple tables. 

https://hasura.io/docs/1.0/graphql/core/schema/views.html

For example, if we get the data for this component

![image](https://user-images.githubusercontent.com/932636/91842445-a79bcd80-ec86-11ea-96c6-2241c4aac3d3.png)

We will need the following query

```graphql
query MyQuery {
  community_pool(limit: 1, order_by: {height: desc}) {
    height
    coins
  }
  token_price(limit: 1, order_by: {timestamp: desc}) {
    price
    timestamp
    market_cap
    denom
  }
  supply(limit: 1, order_by: {height: desc}) {
    coins
    height
  }
  inflation(limit: 1, order_by: {height: desc}) {
    value
    timestamp
    height
  }
}
```
And the result will be

```json
{
  "data": {
    "inflation": [],
    "community_pool": [
      {
        "height": 784563,
        "coins": [
          {
            "denom": "udaric",
            "amount": 2118908.1114036124
          },
          {
            "denom": "upotin",
            "amount": 40.54021548476096
          }
        ]
      }
    ],
    "supply": [
      {
        "coins": [
          {
            "denom": "udaric",
            "amount": 7999952129950
          },
          {
            "denom": "upotin",
            "amount": 80000000000000
          }
        ],
        "height": 784563
      }
    ],
    "token_price": [
      {
        "price": 11896.97,
        "timestamp": "2020-09-01T11:12:08.075512",
        "market_cap": 219816386824,
        "denom": "bitcoin"
      }
    ]
  }
}
```

What if there is an existing view in the database which can prepare the latest result without passing the 4 nearly same parameters to the query? The result may look similar but the graphql query will have better readability.

> but with the downside that it cannot be listened out individually

I don't get what this mean. A view should be like a predefined `SELECT` statement. It should not affect the original structure of the tables.

**Comment by RiccardoM** [comment]
@kwunyeung Let's consider the component you described. 

> I don't get what this mean. A view should be like a predefined SELECT statement. It should not affect the original structure of the tables.

Suppose you have a `VIEW` that has puts together the `community_pool`, `inflation`, `supply` and `token_price`. 

Now what happens is that when something changes, everything gets pushed together, from the `community_pool` to the `token_price`. This means that the refresh of the whole component might become really fast (for example if the `community_pool` is updated every block. 

Instead, what should happen is that you have different subscriptions for each part of that component, and each part only listens to what it truly cares about. The token price should be updated differently from the community pool. It shouldn't be updated all together as this might result in a laggy UX for the user. 

Having multiple subscriptions allows you to also define the maximum changes that single data can push to the subscriber. You can debounce quickly updating subscriptions, or using other strategies. With a single VIEW you can't have this granularity of control and this difference in data handling if every update that is published pushes all the data together.
