### ISSUE TITLE
Update in a new database when chain ID is different

### ISSUE THREAD

**Issue by HarleyAppleChoi** [forbole/bdjuno#44]
## Feature description 
When the chain updated, the block count from zero again. Making a new database to store the data from new chain should persist the data from the old chain as well as logging data from the new chain.
## Implementation proposal
Check chain ID every time when setting up bdjuno. If the chain ID is different from the previous run, make a new database and store data there.

**Comment by HarleyAppleChoi** [comment]
@RiccardoM Is that should be done on juno.db.postgresql.builder?🧐 Can I work on Juno also?

**Comment by RiccardoM** [comment]
@HarleyAppleChoi Currently, the only occasion during which the `chain-id` changes is when a chain gets upgraded. 

A part from changing the chain-id (which *might* happen but it is not granted to), there are other things that might change such as: 

- REST APIs endpoints
- REST APIs returned data
- RPC data format
- Cosmos version
- and so on

For this reason, the best way to upgrade a chain is to upgrade BDJuno (or Juno) if needed as well. You can see an example of this inside DJuno: 

- DJuno `v0.10.0` [relies on Desmos `v0.10.0`](https://github.com/desmos-labs/djuno/blob/v0.10.0/go.mod#L10)
- DJuno `v00.8.1` [relies on Desmos `v0.8.2`](https://github.com/desmos-labs/djuno/blob/v0.8.1/go.mod#L10)
- DJuno `v0.6.2` [relies on Desmos `v0.6.2`](https://github.com/desmos-labs/djuno/blob/v0.6.2/go.mod#L10)
- ...and so on

Since Juno (and its extensions) are thought to run as deamons, there is no way that they can upgrade themselves. For this reason, I think there is a better way to handle this scenario. 

Particularly, the best way possible is to create something like [Cosmosd](https://github.com/regen-network/cosmosd). This tool allows to automatically upgrade a running chain. In our case, our external tool should: 

1. Watch for changes inside the `genesis.json` file.
2. If the `chain-id` inside the `genesis.json` file changes, trigger the upgrade procedure. 

Suppose we are currently running BDJuno listening to the Cosmos chain that has chain-id `cosmoshub-3` and an upgrade is performed changing chain-id to `cosmoshub-4`. Then the upgrade procedure should be composed of the following steps: 

1. Stop the currently running BDJuno. 
2. Upgrade the BDJuno. 
3. Move all the old tables into a backup database (eg. from `cosmoshub` to `cosmoshub-3`). 
4. Create the `cosmoshub` database from scratch. 
5. Start again BDJuno

This would ensure that DBJuno never stops and always upgrades properly. Of course this needs to be handled by another daemon since BDJuno cannot update itself due to the fact that at some point it will have to stop running to be replaced by the new version. 

@kwunyeung Let me know what you think of this as well.

**Comment by kwunyeung** [comment]
@RiccardoM @HarleyAppleChoi `BDJuno` need to store data in an entire new database when the `chain-id` is changed. There was an issue during the upgrade from `morpheus-7001` to `morpheus-8000`. The `BDJuno` was kept running during the upgrade and the data was messed up as the `RPC` and `LCD` are the same.

The step suggested by @RiccardoM should be enough. Instead of moving all tables to a backup database, I would suggest to keep the database name matching the `chain-id` since day 1. Looks like the step should be operated by operator but not `BDJuno` itself to ensure operators is being notified. This can be done by and upgrade command.

Note: by using `x/upgrade`, `chain-id` won't be updated

**Comment by kwunyeung** [comment]
It might not have to be a detection of the manual upgrade. The aim of this issue is to avoid mixing up data from different chains. In the existing database, I see new blocks with block height smaller than those blocks in the database. This means

1. When reading new blocks, BDJuno doesn’t know if the block come from the same chain
2. BDJuno doesn’t know if the block height exist

If we can avoid those situations or throw errors when that happens, at least we can manually setup an new database and new process to parse the new chain from scratch. If there are chances that the blocks from different chains will be mixed up, there are chances that those periodic operations will store wrong results which are irreversible.

**Comment by RiccardoM** [comment]
> I see new blocks with block height smaller than those blocks in the database

This is something wanted. When BDJuno is started, it spawns to different processes: 

1. the one that allows to parse all the old blocks up until the current height; 
2. the one that allows to parse new blocks by listening to the Tendermint websocket. 

If there are a lot of old blocks, it's common that new blocks coming from the websocket will be parsed before older blocks since they are all handled as soon as possible. 

---

> When reading new blocks, BDJuno doesn’t know if the block come from the same chain

This is true, there is no way from Tendermint to know what chain a block refers to. The chain id is something related to Cosmos, not Tendermint. 

---

> BDJuno doesn’t know if the block height exist

It actually does. If a block exists it will still be parsed the block, but the data are not stored it inside the database. 

---

To be honest, as we all know chain updates are something that is programmed weeks or months ahead. For this reason, I think that the upgrade procedure (which includes the export - migration - import) should all be handled by the sysadmin. This includes the stopping - update - start of the new BDJuno instance, which can all be done in just three CLI commands.

**Comment by kwunyeung** [comment]
Ok. Sounds good.
