### ISSUE TITLE
CosmWasm module parse error

### ISSUE THREAD

**Issue by velocent** [forbole/bdjuno#502]
Hello.
My cosmos blockchain has cosmwasm module and get error while fetching block history.
I think bdjuno does not support cosmwasm module parsing.

`ERR re-enqueueing failed block err="failed to get transactions for block: error while unpacking message: no concrete type registered for type URL /cosmwasm.wasm.v1.MsgExecuteContract against interface *types.Msg" height=626425`

**Comment by rmontagnin** [comment]
What branch of BDJuno are you using @Sirius198?

**Comment by velocent** [comment]
I've cloned default(cosmos/0.44.x) branch. @RiccardoM

**Comment by huichiaotsou** [comment]
Hey @Sirius198 the error message you are receiving is probably because [your `app.ModuleBasics` was not added](https://docs.bigdipper.live/cosmos-based/parser/custom-chains#add-your-application-modules). 

To parse `x/wasm` data, I suggest you using `chains/comdex/mainnet` branch since the default branch has no wasm implemented.

please reopen the issue if you need further info.
