### ISSUE TITLE
Question: Validator power events query

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#88]
How do i query this?
Correct me if i'm wrong but would i..
query the voting power by height and each time there is a change find the transaction that caused it?

![image](https://user-images.githubusercontent.com/42913823/106099853-52e97980-6176-11eb-9a5e-723f3e27a53a.png)

**Comment by rmontagnin** [comment]
As far as I know, power changes only in three occasions: 

1. when someone delegates some new tokens, increasing the power
2. when someone re-delegates some tokens, reducing the first validator power and increasing the second one 
3. when someone unbonds some tokens, reducing the validator voting power

I'd like @kwunyeung to confirm this as well. 

If that's the case, you can simply observe for specific messages (`MsgDelegate`, `MsgUnbond`, `MsgBeginRedelegate` and use the data inside those to update the UI). I'd like to know what the current BigDipper UI does though so that we can maybe improve this

**Comment by kwunyeung** [comment]
@ryuash yes that's how I did on the existing Big Dipper. Cosmos SDK change the voting power two blocks after the transaction is committed. You can query the transactions with nearest lower height.

@RiccardoM for transactions, `MsgCreateValidator` and `MsgUnjail` will also make voting power change. There are other cases the voting power will change. When the validator is being jailed and voting power is not enough in the validator set, the voting power will drop from a positive amount to 0.

The voting power change are either an increment or decrement.

Voting power increases when
1. `MsgCreateValidator` (voting power from 0 to positive number)
2. `MsgDelegate` (voting power value increase)
3. `MsgUnjail` and voting power enough be in the validator set  (voting power from 0 to positive number)

Voting power decreases when
1. `MsgUnbond` (voting power decreases, can reach 0 if validator unbond itself)
2. `MsgBeginRedelegate` (voting power decrease in A validator but increase in B validator)
3. validator remove from validator set, can be jail or not enough voting power (voting power decreases to 0)

I haven't tracked the differences between jail and being clicked out from the validator set because of low voting power. I haven't thought of a way to differentiate this by only reading the block yet. Another thing worth noting is that when the voting power changes, it could be because of a series of transactions happening in the same block. For example, two transactions with `MsgDelegate` from two different delegators are delegating to the same validator at the same block H, the voting power of the validator will increase with the sum of both delegations at H+2.
